name: branch

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine3.11
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates python2 python3

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run lint
          npm run test
          npm run build
          npm run package
