name: extractor-branch

on:
  pull_request:
    paths:
      - ".github/workflows/extractor-branch.yaml"
      - "extractor/**"
  push:
    paths:
      - ".github/workflows/extractor-branch.yaml"
      - "extractor/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine3.12
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates bash curl python2 python3

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd extractor
          npm install
          npm run lint
          npm run test
          npm run build
          npm run package

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          file: ./extractor/coverage/clover.xml
          name: extractor
