name: gateway-branch

on:
  pull_request:
    paths:
      - ".github/workflows/gateway-branch.yaml"
      - "gateway/**"
  push:
    paths:
      - ".github/workflows/gateway-branch.yaml"
      - "gateway/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine3.11
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates bash curl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd gateway
          make build-deps deps test
          make fmt
          if [[ $(git diff --stat) != '' ]]; then
            echo 'run make fmt and commit changes'
            exit 1
          fi