name: branch-goreleaser

on:
  pull_request:
    paths:
      - ".github/workflows/goreleaser-branch.yaml"
      - "deps/**"
      - "gateway/**"
      - "indexer/**"
      - "tracker/**"
  push:
    paths:
      - ".github/workflows/goreleaser-branch.yaml"
      - "deps/**"
      - "gateway/**"
      - "indexer/**"
      - "tracker/**"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine3.11
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates curl

      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
          ./bin/goreleaser --snapshot --skip-publish
